<a href="https://colab.research.google.com/github/finningr/late_and_ungraded_work/blob/main/weekly_three.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
def legal_moves(position, player):
    moves = []
    n = len(position)

    for i in range(n):
        if player == "T" and position[i] == "T":
            if i + 1 < n and position[i + 1] == ".":
                board = list(position)
                board[i], board[i + 1] = ".", "T"
                moves.append("".join(board))

            if i + 2 < n and position[i + 1] == "F" and position[i + 2] == ".":
                board = list(position)
                board[i], board[i + 2] = ".", "T"
                moves.append("".join(board))

        if player == "F" and position[i] == "F":
            if i - 1 >= 0 and position[i - 1] == ".":
                board = list(position)
                board[i], board[i - 1] = ".", "F"
                moves.append("".join(board))

            if i - 2 >= 0 and position[i - 1] == "T" and position[i - 2] == ".":
                board = list(position)
                board[i], board[i - 2] = ".", "F"
                moves.append("".join(board))

    return moves


def other_player(player):
    return "F" if player == "T" else "T"

In [ ]:
def minimax_search(position, player):
    nodes_visited = 0

    def search(current_position, current_player):
        nonlocal nodes_visited
        nodes_visited += 1

        moves = legal_moves(current_position, current_player)

        if not moves:
            return -1, None

        best_score = float("-inf")
        best_move = None

        for move in moves:
            opponent_score, _ = search(move, other_player(current_player))
            score = -opponent_score

            if score > best_score:
                best_score = score
                best_move = move

        return best_score, best_move

    score, best_move = search(position, player)
    result = "win" if score == 1 else "loss"

    return result, best_move, nodes_visited

In [ ]:
def alpha_beta_search(position, player):
    nodes_visited = 0

    def search(current_position, current_player, alpha, beta):
        nonlocal nodes_visited
        nodes_visited += 1

        moves = legal_moves(current_position, current_player)

        if not moves:
            return -1, None

        best_score = float("-inf")
        best_move = None

        for move in moves:
            opponent_score, _ = search(
                move,
                other_player(current_player),
                -beta,
                -alpha
            )
            score = -opponent_score

            if score > best_score:
                best_score = score
                best_move = move

            alpha = max(alpha, score)

            if alpha >= beta:
                break

        return best_score, best_move

    score, best_move = search(
        position,
        player,
        float("-inf"),
        float("inf")
    )
    result = "win" if score == 1 else "loss"

    return result, best_move, nodes_visited

In [ ]:
test_cases = [
    ("T.F", "T"),
    ("T.F", "F"),
    ("TT..FF", "T"),
    ("TT..FF", "F"),
    ("TTT...FFF", "T"),
    ("TTT...FFF", "F")
]

In [ ]:
minimax_results = []

for position, player in test_cases:
    result, best_move, nodes = minimax_search(position, player)
    minimax_results.append(
        {
            "position": position,
            "player": player,
            "result": result,
            "best_move": best_move,
            "nodes_visited": nodes
        }
    )

pd.DataFrame(minimax_results)

    position player result  best_move  nodes_visited
0        T.F      T    win        .TF              4
1        T.F      F    win        TF.              4
2     TT..FF      T    win     T.T.FF             20
3     TT..FF      F    win     TT.F.F             20
4  TTT...FFF      T   loss  TT.T..FFF          89864
5  TTT...FFF      F   loss  TTT..F.FF          89864

In [ ]:
alpha_beta_results = []

for position, player in test_cases:
    result, best_move, nodes = alpha_beta_search(position, player)
    alpha_beta_results.append(
        {
            "position": position,
            "player": player,
            "result": result,
            "best_move": best_move,
            "nodes_visited": nodes
        }
    )

pd.DataFrame(alpha_beta_results)

    position player result  best_move  nodes_visited
0        T.F      T    win        .TF              4
1        T.F      F    win        TF.              4
2     TT..FF      T    win     T.T.FF             20
3     TT..FF      F    win     TT.F.F             20
4  TTT...FFF      T   loss  TT.T..FFF           5653
5  TTT...FFF      F   loss  TTT..F.FF           1395

In [ ]:
comparison_results = []

for position, player in test_cases:
    minimax_result, minimax_move, minimax_nodes = minimax_search(position, player)
    alpha_result, alpha_move, alpha_nodes = alpha_beta_search(position, player)

    comparison_results.append(
        {
            "position": position,
            "player": player,
            "minimax_result": minimax_result,
            "minimax_best_move": minimax_move,
            "minimax_nodes": minimax_nodes,
            "alpha_beta_result": alpha_result,
            "alpha_beta_best_move": alpha_move,
            "alpha_beta_nodes": alpha_nodes,
            "nodes_saved": minimax_nodes - alpha_nodes
        }
    )

pd.DataFrame(comparison_results)

,position,player,minimax_result,minimax_best_move,minimax_nodes,alpha_beta_result,alpha_beta_best_move,alpha_beta_nodes,nodes_saved
0,T.F,T,win,.TF,4,win,.TF,4,0
1,T.F,F,win,TF.,4,win,TF.,4,0
2,TT..FF,T,win,T.T.FF,20,win,T.T.FF,20,0
3,TT..FF,F,win,TT.F.F,20,win,TT.F.F,20,0
4,TTT...FFF,T,loss,TT.T..FFF,89864,loss,TT.T..FFF,5653,84211
5,TTT...FFF,F,loss,TTT..F.FF,89864,loss,TTT..F.FF,1395,88469